=== ChenchenC/Programming-Web-Service/XMLProcessing/src/xml/CompanyInfoXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/CompanyInfoXMLSchema"
	xmlns:tns="http://www.example.org/CompanyInfoXMLSchema"
	elementFormDefault="qualified">
	<xsd:element name="Company">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="CompanyInfo" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="CompanyName" type="xsd:string"
								minOccurs="1" />
							<xsd:element name="Address">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Line1" type="xsd:string" />
										<xsd:element name="Line2" type="xsd:string"
											minOccurs="0" />
										<xsd:element name="City" type="xsd:string" />
										<xsd:element name="Country" type="xsd:string" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="YearEstablished" type="xsd:nonNegativeInteger" />
							<xsd:element name="Telephone">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[0-9]{10}" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Fax">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[0-9]{10}" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="PostCode">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[0-9]{5}" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Email" type="xsd:string" />
							<xsd:element name="Website" type="xsd:string" />
							<xsd:element name="EmployeeNumber" type="xsd:positiveInteger" />
							<xsd:element name="CompanyType" type="xsd:string" />
							<xsd:element name="Description" type="xsd:string" />
							<xsd:element name="Contact">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FirstContactName" minOccurs="1"
											maxOccurs="unbounded" type="xsd:string"></xsd:element>
										<xsd:element name="FirstContactTitle" minOccurs="1"
											maxOccurs="unbounded" type="xsd:string"></xsd:element>
										<xsd:element name="SecondContactName" minOccurs="0"
											maxOccurs="unbounded" type="xsd:string"></xsd:element>
										<xsd:element name="SecondContactTitle" minOccurs="0"
											maxOccurs="unbounded" type="xsd:string"></xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>

						<xsd:attribute name="companyId" use="required">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:pattern value="[0-9]{6}" />
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:attribute>
						<xsd:attribute name="submitted" use="required" type="xsd:date" />

					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>
		</xsd:complexType>

	</xsd:element>
</xsd:schema>

=== ChenchenC/Programming-Web-Service/programming web service/XMLProcessing/src/xml/CompanyInfoXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Company xmlns:tns="http://www.example.org/CompanyInfoXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/CompanyInfoXMLSchema CompanyInfoXMLSchema.xsd ">
  <tns:CompanyInfo companyId="000001" submitted="2001-01-01">
    <tns:CompanyName>Max</tns:CompanyName>
    <tns:Address>
      <tns:Line1>Ballmora</tns:Line1>
      <tns:City>Stockholm</tns:City>
      <tns:Country>Sweden</tns:Country>
    </tns:Address>
    <tns:YearEstablished>12</tns:YearEstablished>
    <tns:Telephone>0735569855</tns:Telephone>
    <tns:Fax>0735569855</tns:Fax>
    <tns:PostCode>16453</tns:PostCode>
    <tns:Email>max@sweden.se</tns:Email>
    <tns:Website>http://max.se</tns:Website>
    <tns:EmployeeNumber>1</tns:EmployeeNumber>
    <tns:CompanyType>Food and beverage</tns:CompanyType>
    <tns:Description>Sweden's most successful fast food</tns:Description>
    <tns:Contact>
      <tns:FirstContactName>Maxy</tns:FirstContactName>
      <tns:FirstContactTitle>Founder</tns:FirstContactTitle>
    </tns:Contact>
  </tns:CompanyInfo>
  <tns:CompanyInfo companyId="000002" submitted="2001-01-01">
    <tns:CompanyName>Kentucky Fried Chicken</tns:CompanyName>
    <tns:Address>
      <tns:Line1>Farsta</tns:Line1>
      <tns:City>Stockholm</tns:City>
      <tns:Country>Sweden</tns:Country>
    </tns:Address>
    <tns:YearEstablished>0</tns:YearEstablished>
    <tns:Telephone>0735569856</tns:Telephone>
    <tns:Fax>0735569856</tns:Fax>
    <tns:PostCode>16453</tns:PostCode>
    <tns:Email>kentucky@kth.se</tns:Email>
    <tns:Website>http://kentucky.com</tns:Website>
    <tns:EmployeeNumber>1</tns:EmployeeNumber>
    <tns:CompanyType>Food and Beverage</tns:CompanyType>
    <tns:Description>The world's biggest fried chicken restaurant</tns:Description>
    <tns:Contact>
      <tns:FirstContactName>Kentucky</tns:FirstContactName>
      <tns:FirstContactTitle>Founder</tns:FirstContactTitle>
    </tns:Contact>
  </tns:CompanyInfo>
</tns:Company>
