=== ChenchenC/Programming-Web-Service/XMLProcessing/src/xml/employmentRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/EmploymentRecXMLSchema"
	xmlns:tns="http://www.example.org/EmploymentRecXMLSchema"
	elementFormDefault="qualified">
	<xsd:annotation>
		<xsd:documentation>
			This schema captures the employment record details.
		</xsd:documentation>
	</xsd:annotation>

	<xsd:element name="employmentRecord">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="person" >
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="firstName" type="xsd:string" minOccurs="1"/>
							<xsd:element name="lastName" type="xsd:string" minOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="gender" minOccurs="1">
					<xsd:simpleType >
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="female"/>
							<xsd:enumeration value="male"/>
							<xsd:enumeration value="notClear"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="jobRecord" maxOccurs="unbounded" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="company" type="xsd:string" />
							<xsd:element name="startOfEmployment" type="xsd:date" />
							<xsd:element name="endOfEmployment" type="xsd:date" />
							<xsd:element name="department" type="xsd:string" />
							<xsd:element name="position" type="xsd:string">
								<!-- <xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="([a-z])*" />
									</xsd:restriction>
								</xsd:simpleType> -->
							</xsd:element>
							<xsd:element name="salary" type="xsd:decimal" />
							<xsd:element name="jobDesc" type="xsd:string" />
							<xsd:element name="jobType">
								<xsd:simpleType >
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="part-time"/>
										<xsd:enumeration value="permanent"/>
										<xsd:enumeration value="contract"/>
										<xsd:enumeration value="other"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" use="required"> 
					<xsd:simpleType >
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="[0-9]{6}"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="submitted" use="required" type="xsd:dateTime"/>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== ChenchenC/Programming-Web-Service/programming web service/XMLProcessing/src/xml/employmentRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:employmentRecord id="000001" submitted="2001-12-31T12:00:00" xmlns:tns="http://www.example.org/EmploymentRecXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/EmploymentRecXMLSchema employmentRecord.xsd ">
  <tns:person>
    <tns:firstName>John</tns:firstName>
    <tns:lastName>Yusof</tns:lastName>
  </tns:person>
  <tns:gender>male</tns:gender>
  <tns:jobRecord>
    <tns:company>Maxs</tns:company>
    <tns:startOfEmployment>2011-02-01</tns:startOfEmployment>
    <tns:endOfEmployment>2017-01-01</tns:endOfEmployment>
    <tns:department>Kitchen</tns:department>
    <tns:position>Head Chef</tns:position>
    <tns:salary>4000</tns:salary>
    <tns:jobDesc>In charge of managing the staffs in the kitchen to ensure that the kitchen is in running order</tns:jobDesc>
    <tns:jobType>contract</tns:jobType>
  </tns:jobRecord>
  <tns:jobRecord>
    <tns:company>Kentucky Fried Chicken Restaurant</tns:company>
    <tns:startOfEmployment>2001-01-01</tns:startOfEmployment>
    <tns:endOfEmployment>2011-01-01</tns:endOfEmployment>
    <tns:department>Kitchen</tns:department>
    <tns:position>Chef</tns:position>
    <tns:salary>3500</tns:salary>
    <tns:jobDesc>Incharge of frying the chickens up to satisfactory standards of KFC</tns:jobDesc>
    <tns:jobType>part-time</tns:jobType>
  </tns:jobRecord>
</tns:employmentRecord>
