=== ChenchenC/Programming-Web-Service/XMLProcessing/src/xml/ShortCVXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ShortCVXMLSchema" xmlns:tns="http://www.example.org/ShortCVXMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="ShortCV">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="FirstName" type="xsd:string"
					minOccurs="1" />
				<xsd:element name="LastName" type="xsd:string"
					minOccurs="1" />
				<xsd:element name="PersonalNumber" minOccurs="1">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="[0-9]{10}" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="Gender" minOccurs="1">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="female" />
							<xsd:enumeration value="male" />
							<xsd:enumeration value="notClear" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="Birthday" minOccurs="1" type="xsd:date" />
				<xsd:element name="Nationality" type="xsd:string" />
				<xsd:element name="Address" type="xsd:string" />
				<xsd:element name="Email" type="xsd:string" />
				<xsd:element name="Telephone">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="[0-9]{10}" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="LinkedinUrl" type="xsd:string" />
				<xsd:element name="Achievements" type="xsd:string" />
				<xsd:element name="Skills" type="xsd:string" />
				<xsd:element name="MotivationExplanation" type="xsd:string" />
				<xsd:element name="JobType">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="part-time" />
							<xsd:enumeration value="permanent" />
							<xsd:enumeration value="contract" />
							<xsd:enumeration value="other" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="DesiredWorkplace" minOccurs="1"
								maxOccurs="unbounded" type="xsd:string">
				</xsd:element>
			<!-- 	<xsd:element name="References" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence> -->

							<xsd:element name="RecommenderName" minOccurs="1"
								maxOccurs="unbounded" type="xsd:string"></xsd:element>
							<xsd:element name="Relation" minOccurs="1" maxOccurs="unbounded"
								type="xsd:string"></xsd:element>
							<xsd:element name="Organization" minOccurs="1"
								maxOccurs="unbounded" type="xsd:string"></xsd:element>
							<xsd:element name="Content" minOccurs="1" maxOccurs="unbounded"
								type="xsd:string"></xsd:element>

	<!-- </xsd:sequence> </xsd:complexType> </xsd:element> -->
			</xsd:sequence>

			<xsd:attribute name="id" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[0-9]{6}" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="submitted" use="required" type="xsd:date" />

		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== ChenchenC/Programming-Web-Service/XMLProcessing/src/xml/ShortCVXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet type="text/xsl" href="../method/ShortCVProcessor.xsl"?> -->
<ShortCV id="000001" submitted="2001-01-01"
	xmlns="http://www.example.org/ShortCVXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ShortCVXMLSchema ShortCVXMLSchema.xsd ">
	<FirstName>John</FirstName>
	<LastName>Yusof</LastName>
	<PersonalNumber>9208226154</PersonalNumber>
	<Gender>female</Gender>
	<Birthday>2001-01-01</Birthday>
	<Nationality>Indian</Nationality>
	<Address>Farsta, Sweden</Address>
	<Email>john.yusof@gmail.com</Email>
	<Telephone>0735569855</Telephone>
	<LinkedinUrl>-</LinkedinUrl>
	<Achievements>3rd runner up in marathon</Achievements>
	<Skills>Driving license, Diploma in powerpoint</Skills>
	<MotivationExplanation>I wish to find a job that motivates me to go to work every morning.</MotivationExplanation>
	<JobType>part-time</JobType>
	<DesiredWorkplace>
	StockHolm
	</DesiredWorkplace>
		<RecommenderName>Mr. Kentucky</RecommenderName>
		<Relation>Supervisor</Relation>
		<Organization>Kentucy Fried Chicken</Organization>
		<Content>Mr. Yusof is a highly motivated individual who neer fails to disappoint.</Content>
</ShortCV>
