=== ChenchenC/Programming-Web-Service/XMLProcessing/src/xml/transcript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/TranscriptXMLSchema" xmlns:tns="http://www.example.org/TranscriptXMLSchema"
	elementFormDefault="qualified">
	<xsd:annotation>
		<xsd:documentation>
			This schema captures the transcript details.
		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="transcript">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="person">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="firstName" type="xsd:string"
								minOccurs="1" />
							<xsd:element name="lastName" type="xsd:string"
								minOccurs="1" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="university" type="xsd:string" />
				<xsd:element name="degree">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="Undergraduate" />
							<xsd:enumeration value="Masters" />
							<xsd:enumeration value="Doctorate" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>

				<xsd:element name="gradePointAverage" type="xsd:decimal" />
				<xsd:element name="dateOfGraduation" type="xsd:date" />
				<xsd:element name="dateOfEnrolment" type="xsd:date" />

				<xsd:element name="module" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="moduleName" type="xsd:string" />

							<xsd:element name="moduleCodePrefix">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="([A-Z])*" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="moduleCodeSuffix">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="([0-9])*" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="moduleGrade">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="A" />
										<xsd:enumeration value="B" />
										<xsd:enumeration value="C" />
										<xsd:enumeration value="D" />
										<xsd:enumeration value="E" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="moduleCredits" type="xsd:decimal" />
							<xsd:element name="moduleTerm" type="xsd:string" />
							<xsd:element name="moduleYear" type="xsd:int" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>
			<xsd:attribute name="id" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[0-9]{6}" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="submitted" use="required" type="xsd:dateTime" />
		</xsd:complexType>

	</xsd:element>

</xsd:schema>

=== ChenchenC/Programming-Web-Service/programming web service/XMLProcessing/src/xml/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:transcript id="123456" submitted="2001-12-31T12:00:00"
	xmlns:tns="http://www.example.org/TranscriptXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/TranscriptXMLSchema transcript.xsd ">
	<tns:person>
		<tns:firstName>John</tns:firstName>
		<tns:lastName>Yusof</tns:lastName>
	</tns:person>
	<tns:university>KTH</tns:university>
	<tns:degree>Undergraduate</tns:degree>
	<tns:gradePointAverage>0.0</tns:gradePointAverage>
	<tns:dateOfGraduation>1994-01-01</tns:dateOfGraduation>
	<tns:dateOfEnrolment>1991-01-01</tns:dateOfEnrolment>
	<tns:module>
		<tns:moduleName>Programming Web Service</tns:moduleName>
		<tns:moduleCodePrefix>ME</tns:moduleCodePrefix>
		<tns:moduleCodeSuffix>2015</tns:moduleCodeSuffix>
		<tns:moduleGrade>A</tns:moduleGrade>
		<tns:moduleCredits>7.5</tns:moduleCredits>
		<tns:moduleTerm>Summer</tns:moduleTerm>
		<tns:moduleYear>2017</tns:moduleYear>
	</tns:module>
	<tns:module>
		<tns:moduleName>Economics of Innovation</tns:moduleName>
		<tns:moduleCodePrefix>ME</tns:moduleCodePrefix>
		<tns:moduleCodeSuffix>2711</tns:moduleCodeSuffix>
		<tns:moduleGrade>D</tns:moduleGrade>
		<tns:moduleCredits>6.0</tns:moduleCredits>
		<tns:moduleTerm>Spring</tns:moduleTerm>
		<tns:moduleYear>2016</tns:moduleYear>
	</tns:module>
	<tns:module>
		<tns:moduleName>Intercultural Communication</tns:moduleName>
		<tns:moduleCodePrefix>DM</tns:moduleCodePrefix>
		<tns:moduleCodeSuffix>2556</tns:moduleCodeSuffix>
		<tns:moduleGrade>B</tns:moduleGrade>
		<tns:moduleCredits>6.0</tns:moduleCredits>
		<tns:moduleTerm>Spring</tns:moduleTerm>
		<tns:moduleYear>2016</tns:moduleYear>
	</tns:module>
	<tns:module>
		<tns:moduleName>Internet Networking</tns:moduleName>
		<tns:moduleCodePrefix>AK</tns:moduleCodePrefix>
		<tns:moduleCodeSuffix>2759</tns:moduleCodeSuffix>
		<tns:moduleGrade>C</tns:moduleGrade>
		<tns:moduleCredits>6.0</tns:moduleCredits>
		<tns:moduleTerm>Spring</tns:moduleTerm>
		<tns:moduleYear>2016</tns:moduleYear>
	</tns:module>
</tns:transcript>
